### ISSUE TITLE
你的这个库怎么使用

### ISSUE THREAD

**Issue by renxiaowang** [Jiavan/vanjs#1]
文件太多，看的有些晕

**Comment by Jiavan** [comment]
目前可以用的是1.0版本，里面的接口除了Ajax部分基本都做了测试。
源文件在`/src`下的`van.js`直接引入就行了，目前还存在一些兼容性问题，所以有2.0版本正在开发，打算写得更健壮一些，遵循模块化的一些规范，有兴趣可以一起探讨哈 : )

**Comment by renxiaowang** [comment]
多谢
